ALTER TABLE customers
    ADD COLUMN IF NOT EXISTS nome VARCHAR(120),
    ADD COLUMN IF NOT EXISTS telefone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS observacoes VARCHAR(600),
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP WITH TIME ZONE;

ALTER TABLE trips
    ADD COLUMN IF NOT EXISTS cliente_id BIGINT,
    ADD COLUMN IF NOT EXISTS data_hora_agendada TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS km_rodados NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS valor_bruto NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS taxa_plataforma NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS valor_liquido NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS despesas NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS lucro NUMERIC(12,2);

ALTER TABLE expenses
    ADD COLUMN IF NOT EXISTS corrida_id BIGINT,
    ADD COLUMN IF NOT EXISTS tipo_despesa VARCHAR(30),
    ADD COLUMN IF NOT EXISTS valor NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS data_hora TIMESTAMP WITH TIME ZONE;

ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS corrida_id BIGINT,
    ADD COLUMN IF NOT EXISTS cliente_id BIGINT,
    ADD COLUMN IF NOT EXISTS valor NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS data_hora_pagamento TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS data_hora_vencimento TIMESTAMP WITH TIME ZONE;

ALTER TABLE app_users
    ADD COLUMN IF NOT EXISTS nome VARCHAR(120),
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP WITH TIME ZONE;
